### ISSUE TITLE
hotkeys quit working

### ISSUE THREAD

**Issue by netfun81** [bblhd/crwm#1]
I like this wm concept of changing tiling modes manually.  Ran into an issue when using Mod-# to change desktops and when pressing Mod-d on new desktop to activate dmenu, the hotkeys no longer respond, nothing happens when pressing any hotkey.  It doesnt crash the wm but cannot launch anything or switch to other desktops.

**Comment by bblhd** [comment]
Thanks for trying my wm! Does trying to input a hotkey type the key you pressed on the focused window, or does nothing happen in both the wm and focused window? I assume that dmenu_run is working.

**Comment by netfun81** [comment]
I see you made some changes so I downloaded the latest and tried again.  It still happens when having applications open on the first two virtual desks and then switching to a third with mod-3, pressing mod-d will no longer run dmenu, and mod-return mod-1 mod-2 do nothing. Will try to look into it more later.

**Comment by bblhd** [comment]
Thanks for the help, I suspect that its either the wm entering into an infinite loop or that X stops sending it the keypresses for some reason, so it would be good to rule either of those out.

I've tried replicating your error on 4 different computers and I haven't been able to yet, but they all use the same setup, so that could be why. Could you tell me what distro/dm/etc you use so I could perhaps try it on that?

**Comment by netfun81** [comment]
I'm on Arch linux with lightdm as the display manager.  It may be an app causing the issue, i'm mostly using firefox, thunar, alacritty, geany, and xfce apps.  I do have xfce4-power-manager running in background.  Will try to see if its a particular desktop or app that confuses it, hopefully have some time this weekend to test.

**Comment by bblhd** [comment]
I still can't recreate the error, could be something out-of-date, or anything really I don't know. Anyway, I'm planning on reimplementing it from scratch soon because of systematic issues, specifically in how desktops are managed.

Does dwm work without error for you? If so I can refer to it to make sure window handling in future is done correctly

**Comment by bblhd** [comment]
Just thought I should add to this issue that I've updated crwm which should _hopefully_ fix some stability issues (fingers crossed).

**Comment by netfun81** [comment]
Thanks, It appears you fixed the hotkey issue since they havent stopped working.  I did run into another issue when having two windows opened and tiled vertically, pressing Mod-Shift-Left or Right causes the window manager to crash.

**Comment by bblhd** [comment]
Thats great (that the original issue is fixed). I also have the new error, it seems to only affect x86 computers and not arm, which is why i didnt notice it before.

Im going to close this issue and open a new one for the new problem.

**Comment by bblhd** [comment]
#4

**Comment by bblhd** [comment]
It should bee fixed now
